### PR TITLE
Remove Community reference

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by rackernexus** [comment]
Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by cyrichardson** [comment]
(This content is no longer published externally. Hence the message above.)

**Comment by jfwood** [comment]
Hello @cyrichardson, I worked on the cloud keep team a while back, and the project has been cancelled for a while now. It seems all references to cloud keep should be removed?

**Comment by cyrichardson** [comment]
Thanks, @jfwood. Yes, the repo is noted as deprecated. But in case anyone ever references this repo we wanted to remove any Community references because Community is going away as of 1/21/2019.

As far as Cloud Keep goes, I will check other API and How-To docs to see if there are any references to Cloud Keep.

**Pull request merged**
